- name: Backup de configuração
  hosts: all
  gather_facts: yes

  tasks:

    - name: Incluir role
      include_role:
        name: clay584.parse_genie

    - name: Get arp
      ios_command:
        commands: show arp
      register: arp_output

    - name: Print role
      debug:
        msg: "{{ arp_output['stdout'][0] | parse_genie(command='show arp', os='iosxe') }}"
